"""Add description to game_sessions

Revision ID: 35d96c47bf00
Revises: 90f6bc87253e
Create Date: 2026-04-09 10:15:10.644574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d96c47bf00'
down_revision: Union[str, None] = '90f6bc87253e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'credit_batches', ['order_id'])
    op.add_column('game_sessions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'description')
    op.drop_constraint(None, 'credit_batches', type_='unique')
    # ### end Alembic commands ###