"""add_funding_gm_reward

Revision ID: a9f56866ec22
Revises: 4b1c70660c72
Create Date: 2026-03-30 16:23:08.543615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f56866ec22'
down_revision: Union[str, None] = '4b1c70660c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    campaignfunding = sa.Enum('club', 'private', name='campaignfunding')
    campaignfunding.create(op.get_bind(), checkfirst=True)
    op.add_column('campaigns', sa.Column('funding', sa.Enum('club', 'private', name='campaignfunding'), server_default='club', nullable=False))
    op.add_column('credit_batches', sa.Column('session_id', sa.Integer(), nullable=True))
    op.alter_column('credit_batches', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'credit_batches', 'game_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_batches', type_='foreignkey')
    op.alter_column('credit_batches', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('credit_batches', 'session_id')
    op.drop_column('campaigns', 'funding')
    # ### end Alembic commands ###